server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    enableSelfPreservation: false
    leaseRenewalIntervalInSeconds: 2

spring:
  application:
    name: eurka-server